config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'conversations#index'
  resources :groups do
    resources :members
    resources :conversations do
      resources :messages
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :members
  has_many :messages
  
  accepts_nested_attributes_for :messages
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :members
  has_many :conversations

  accepts_nested_attributes_for :members

  validates :name, presence: true, length: { minimum: 2 }
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :member
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name])
  end
end

app/controllers/conversations_controller.rb
require 'pry'
class ConversationsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @admin_groups = Group.where(user_id: current_user.id) if user_signed_in?
    @conversations = Conversation.all.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @conversation = Conversation.new(group_id: params[:group_id])
  end

  def create
    @conversation = Conversation.new(conversation_params)
    @conversation.user_id = current_user.id
    @group = Group.find(params[:group_id])
    if @conversation.save
      redirect_to new_group_conversation_message_path(@group, @conversation)
    else
      render :new
    end
  end

  private

  def conversation_params
    params.require(:conversation).permit(:title, :group_id, messages_attributes: [:content, :group_id, :member_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @admin_groups = Group.where(user_id: current_user.id).order(created_at: :desc)
    @group = Group.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.members.order(nick_name: :asc)
    @member = Member.new(group_id: @group.id)
    @conversations = @group.conversations.order(created_at: :desc)
  end

  private

  def group_params
    params.require(:group).permit(:name, members_attributes: [:nick_name, :group_id])
  end
end

app/controllers/members_controller.rb
  require 'pry'
class MembersController < ApplicationController
  def index
    @group = Group.find(member_params.group_id)
    @member.where(group_id: @group.id)
  end
  
  def new
    @group = Group.find(params[:group_id])
    @member = Member.new(group: @group)
  end
  
  def create
    @member = Member.new(member_params)
    # binding.pry
    @group = Group.find(@member.group_id)
    if @member.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  private
  
  def member_params
    params.require(:member).permit(:nick_name, :group_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @messages = Message.where(conversation_id: params[:conversation_id]).order(created_at: :asc)
    @message = Message.new(conversation_id: params[:conversation_id])
    @members = Member.where(group_id: params[:group_id])
  end

  def create
    @message = Message.new(message_params)
    @conversation = Conversation.find(@message.conversation_id)
    @group = Group.find(@conversation.group_id)
    if @message.save
      redirect_to new_group_conversation_message_path(@group, @conversation)
    else
      render :new
    end
  end
  
  private
  
  def message_params
    params.require(:message).permit(:content, :conversation_id, :member_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/index.html.erb
<h1>Family gems</h1>
<% if user_signed_in? %>
  <%= link_to "Create a new group", new_group_path %>
  <br>
  <% if user_signed_in? && current_user.groups.any? %>
    <h2>Your groups</h2>
    <ul>
      <% @admin_groups.each do |group| %>
        <li> <%= group.name %> - <%= link_to "Add a new gem", new_group_conversation_path(group), class: "btn btn-primary btn-sm"  %></li>
      <% end %>
    </ul>
  <% elsif !user_signed_in? %>
    <%= link_to "Log in or Sign up", new_user_session_path %>
  <% end %>
<% end %>

<h2>Conversations</h2>
<ul>
  <% @conversations.each do |convo| %>
    <li><%= convo.title %></li>
    <ul>
      <% convo.messages.each do |message| %>
        <li><%= message.member.nick_name %> - <%= message.content %></li>
      <% end %>
    </ul>
  <% end %>
</ul>

app/views/conversations/new.html.erb
<h1>Create a new gem</h1>

<% if @conversation.errors.any? %>
  <% @conversation.errors.full_messages.each do |message|%>\
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<%= form_with model: [:group, @conversation] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.hidden_field :group_id %>
  <br>
  <%= f.submit "Create gem", class: "btn btn-primary" %>
<% end %>

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
  <% @group.errors.full_messages.each do |message|%>\
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<%= form_with model: @group do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create group", class: "btn btn-primary" %>
<% end %>

app/views/groups/_group.html.erb
<ul>
  <%= turbo_frame_tag dom_id(group) do %>
    <li><%= link_to group.name, group_path(group) %></li>
  <% end %>
</ul>

app/views/groups/_member.html.erb
<ul>
  <%= turbo_frame_tag dom_id(member) do %>
    <li><%= member.nick_name %></li>
  <% end %>
</ul>

app/views/groups/_member_form.html.erb
<%= form_with model: [@group, @member] do |m| %>
  <%= m.label :nick_name %>
  <%= m.text_field :nick_name %>
  <%= m.hidden_field :group_id %>
  <%= m.submit "Add member", class: "btn btn-primary" %>
<% end %>

app/views/groups/index.html.erb
<h1>Your groups</h1>

<%= turbo_stream_from "groups" %>

<%= turbo_frame_tag "group_form" do %>
  <%= render "form", group: @group %>
<% end %>

<%= turbo_frame_tag "groups" do %>
  <%= render @admin_groups %>
<% end %>

app/views/groups/new.html.erb
<h1>Create a new group</h1>

<%= render "form" %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<h2>Admin: <%= @group.user.nick_name %></h2>

<%= turbo_stream_from "members" %>

<%= turbo_frame_tag "member_form" do%>
  <%= render "member_form", member: @member %>
<% end %>

<%= turbo_frame_tag "members" do %>
  <%= render @members %>
<% end %>

<%= link_to "Add a new gem", new_group_conversation_path(@group), class: "btn btn-primary"  %>
<ul>
  <% @conversations.each do |convo| %>
    <li><%= convo.title %></li>
    <ul>
      <% convo.messages.each do |message| %>
        <li><%= message.member.nick_name %> - <%= message.content %></li>
      <% end %>
    </ul>
    
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyGems</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/_member.html.erb
<ul>
  <%= turbo_frame_tag dom_id(member) do %>
    <li><%= member.nick_name %></li>
  <% end %>
</ul>

app/views/members/new.html.erb
<h1>Add members to <%= @group.name %> </h1>

<%= form_with model: [:group, @member] do |f| %>
  <%= f.label :nick_name %>
  <%= f.text_field :nick_name %>
  <%= f.hidden_field :group_id %>
  <%= f.submit "Add member", class: "btn btn-primary" %>
<% end %>

app/views/messages/new.html.erb
<h1>Create a new message</h1>

<% if @message.errors.any? %>
  <% @message.errors.full_messages.each do |message|%>\
  <h3><%= message %> </h3>
  <%end%>
<%end%>

<ul>
  <% @messages.each do |message| %>
    <li><%= message.member.nick_name %> - <%= message.content %></li>
  <% end %>
</ul>

<%= form_with model: [:group, :conversation, @message] do |f| %>
  <%= f.label :member %>
  <%= f.collection_select :member_id, @members, :id, :nick_name  %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.hidden_field :conversation_id %>
  <%= f.submit "Add message to conversation", class: "btn btn-primary" %>
  <br>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My groups", groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      <% end %>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Home", root_path, class: "dropdown-item" %>
          <% if user_signed_in? %>
              <%= link_to "My groups", groups_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>